---
swagger: "2.0"
info:
  version: "version not set"
  title: "user.proto"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /api/v1/user/auth:
    post:
      tags:
      - "User"
      operationId: "UserAuth"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/binacs_api_user_v1UserAuthReq"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/binacs_api_user_v1UserAuthResp"
        default:
          description: "An unexpected error response"
          schema:
            $ref: "#/definitions/runtimeError"
  /api/v1/user/info:
    post:
      tags:
      - "User"
      operationId: "UserInfo"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/binacs_api_user_v1UserInfoReq"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/binacs_api_user_v1UserInfoResp"
        default:
          description: "An unexpected error response"
          schema:
            $ref: "#/definitions/runtimeError"
  /api/v1/user/refresh:
    post:
      tags:
      - "User"
      operationId: "UserRefresh"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/binacs_api_user_v1UserRefreshReq"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/binacs_api_user_v1UserRefreshResp"
        default:
          description: "An unexpected error response"
          schema:
            $ref: "#/definitions/runtimeError"
  /api/v1/user/register:
    post:
      tags:
      - "User"
      operationId: "UserRegister"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/binacs_api_user_v1UserRegisterReq"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/binacs_api_user_v1UserRegisterResp"
        default:
          description: "An unexpected error response"
          schema:
            $ref: "#/definitions/runtimeError"
  /api/v1/user/test:
    post:
      tags:
      - "User"
      operationId: "UserTest"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/binacs_api_user_v1UserTestReq"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/binacs_api_user_v1UserTestResp"
        default:
          description: "An unexpected error response"
          schema:
            $ref: "#/definitions/runtimeError"
definitions:
  binacs_api_user_v1UserAuthReq:
    type: "object"
    properties:
      id:
        type: "string"
      pwd:
        type: "string"
  binacs_api_user_v1UserAuthResp:
    type: "object"
    properties:
      code:
        type: "string"
        format: "int64"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/binacs_api_user_v1UserTokenObj"
    example:
      msg: "msg"
      code: "code"
      data:
        access_token: "access_token"
        refresh_token: "refresh_token"
        expire_time: "expire_time"
  binacs_api_user_v1UserInfoObj:
    type: "object"
    properties:
      id:
        type: "string"
      role:
        type: "string"
      desc:
        type: "string"
      ctime:
        type: "string"
      more:
        type: "array"
        items:
          type: "string"
    title: "UserInfo"
    example:
      role: "role"
      more:
      - "more"
      - "more"
      ctime: "ctime"
      id: "id"
      desc: "desc"
  binacs_api_user_v1UserInfoReq:
    type: "object"
    properties:
      access_token:
        type: "string"
  binacs_api_user_v1UserInfoResp:
    type: "object"
    properties:
      code:
        type: "string"
        format: "int64"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/binacs_api_user_v1UserInfoObj"
    example:
      msg: "msg"
      code: "code"
      data:
        role: "role"
        more:
        - "more"
        - "more"
        ctime: "ctime"
        id: "id"
        desc: "desc"
  binacs_api_user_v1UserRefreshReq:
    type: "object"
    properties:
      refresh_token:
        type: "string"
    title: "UserRefresh"
  binacs_api_user_v1UserRefreshResp:
    type: "object"
    properties:
      code:
        type: "string"
        format: "int64"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/binacs_api_user_v1UserTokenObj"
    example:
      msg: "msg"
      code: "code"
      data:
        access_token: "access_token"
        refresh_token: "refresh_token"
        expire_time: "expire_time"
  binacs_api_user_v1UserRegisterDataObj:
    type: "object"
    properties:
      id:
        type: "string"
      pwd:
        type: "string"
    title: "UserRegister"
    example:
      id: "id"
      pwd: "pwd"
  binacs_api_user_v1UserRegisterReq:
    type: "object"
    properties:
      id:
        type: "string"
      pwd:
        type: "string"
  binacs_api_user_v1UserRegisterResp:
    type: "object"
    properties:
      code:
        type: "string"
        format: "int64"
      msg:
        type: "string"
      data:
        $ref: "#/definitions/binacs_api_user_v1UserRegisterDataObj"
    example:
      msg: "msg"
      code: "code"
      data:
        id: "id"
        pwd: "pwd"
  binacs_api_user_v1UserTestReq:
    type: "object"
  binacs_api_user_v1UserTestResp:
    type: "object"
    properties:
      code:
        type: "string"
        format: "int64"
      msg:
        type: "string"
    example:
      msg: "msg"
      code: "code"
  binacs_api_user_v1UserTokenObj:
    type: "object"
    properties:
      access_token:
        type: "string"
      expire_time:
        type: "string"
        format: "int64"
      refresh_token:
        type: "string"
    title: "UserAuth"
    example:
      access_token: "access_token"
      refresh_token: "refresh_token"
      expire_time: "expire_time"
  protobufAny:
    type: "object"
    properties:
      type_url:
        type: "string"
      value:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
  runtimeError:
    type: "object"
    properties:
      error:
        type: "string"
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      details:
        type: "array"
        items:
          $ref: "#/definitions/protobufAny"
